# Generated by Django 3.2.6 on 2021-09-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_cliente_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(choices=[('C', 'CEDULA'), ('D', 'DPI')], default='C', max_length=20),
        ),
    ]
