# Generated by Django 3.2.6 on 2021-09-16 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210916_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('carne', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('contenido', models.CharField(max_length=500)),
                ('fecha', models.DateTimeField()),
                ('Admins', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.admins')),
                ('Estudiantes', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.estudiantes')),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(choices=[('C', 'CEDULA'), ('D', 'DPI')], default='C', max_length=20),
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=500)),
                ('fecha', models.DateTimeField()),
                ('Articulos', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.articulos')),
                ('Estudiantes', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.estudiantes')),
            ],
        ),
    ]
